os: osx
osx_image: xcode11.3
language: swift

jobs:
  include:
    - stage: Unit Tests iOS 13
      script: ./run-swiftpm-tests.sh --ios=13 --test=unit
    - stage: Integration Tests iOS 13
      script: ./run-swiftpm-tests.sh --ios=13 --test=integration
