os: osx
osx_image: xcode11.3
language: swift
git:
  depth: 1

jobs:
  include:
    - stage: Unit Tests iOS 13
      script: ./run-swiftpm-tests.sh --ios=13 --test=unit
    - stage: Integration Tests iOS 13
      script: ./run-swiftpm-tests.sh --ios=13 --test=integration
    - stage: Unit Tests iOS 12
      script: ./run-swiftpm-tests.sh --ios=12 --test=unit
    - stage: Integration Tests iOS 12
      script: ./run-swiftpm-tests.sh --ios=12 --test=integration

after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
